### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'Conv2d_1a_3x3'

### ISSUE THREAD

**Issue by gden138** [larry-11/Self-Supervised-GAN#2]
Thank you for your great work, but I ran it with the following error:
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main(args)
  File "main.py", line 22, in main
    model.train(train_loader)
  File "/home/cy/guo/Self-Supervised-GAN-master/models/sslgan_sn.py", line 339, in train
    fid_value = calculate_fid_given_images(fake_images, self.forzen_images)
  File "/home/cy/guo/Self-Supervised-GAN-master/utils/fid_score.py", line 212, in calculate_fid_given_images
    model = InceptionV3([block_idx])
  File "/home/cy/guo/Self-Supervised-GAN-master/utils/inception.py", line 86, in __init__
    inception.Conv2d_1a_3x3,
AttributeError: 'dict' object has no attribute 'Conv2d_1a_3x3'

what should I do？
Thank you very much！

**Comment by larry-11** [comment]
@gden138 Something wrong in the FID_WEIGHT loading. You can try the newly uploaded version and check here: 
https://github.com/larry-11/Self-Supervised-GAN/blob/f2e3a4004c9d2e8ecbeb9a18942a1aad73c2875b/utils/inception.py#L189

**Comment by gden138** [comment]
@larry-11 
Thank you very much，I have changed code，but new error：
(ssgan) cy@cy-PT6630WN:~/guo/Self-Supervised-GAN-master$ CUDA_VISIBLE_DEVICES=1 python main.py  --model SSLGAN_SN                                        --is_train True                                        --download False                                        --dataroot ../datasets/cifar10                                        --dataset cifar                                        --generator_iters 25000                                        --cuda True                                        --batch_size 12                                        --ssup
True
init model.
Namespace(batch_size=12, channels=3, cuda=True, dataroot='../datasets/cifar10', dataset='cifar', download='False', epochs=50, generator_iters=25000, is_train='True', load_D='False', load_G='False', loss='hinge', model='SSLGAN_SN', ssup=True)
True
Cuda enabled flag: True
WARNING:tensorflow:From /home/cy/guo/Self-Supervised-GAN-master/utils/tensorboard_logger.py:12: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

/home/cy/anaconda3/envs/ssgan/lib/python3.6/site-packages/torchvision/transforms/transforms.py:220: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Files already downloaded and verified
Files already downloaded and verified
/home/cy/guo/Self-Supervised-GAN-master/models/sslgan_sn.py:60: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rot_prob = self.softmax(rot_logits)
Generator iteration: 0/25000, g_loss: -1.3289821147918701, rot_loss: 1.7265498638153076
Models save to ./generator.pkl & ./discriminator.pkl
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main(args)
  File "main.py", line 22, in main
    model.train(train_loader)
  File "/home/cy/guo/Self-Supervised-GAN-master/models/sslgan_sn.py", line 326, in train
    fake_images = self.G(self.frozen_latent)
  File "/home/cy/anaconda3/envs/ssgan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cy/guo/Self-Supervised-GAN-master/models/sslgan_sn.py", line 102, in forward
    d4 = self.re3(d3)
  File "/home/cy/anaconda3/envs/ssgan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cy/guo/Self-Supervised-GAN-master/ops.py", line 130, in forward
    return self.upsample(input) + x
RuntimeError: CUDA out of memory. Tried to allocate 1000.00 MiB (GPU 0; 10.76 GiB total capacity; 7.81 GiB already allocated; 765.56 MiB free; 9.18 GiB reserved in total by PyTorch)
my --batch_size 12

**Comment by gden138** [comment]
@larry-11 
when  my --batch_size 64 ，error is：

(ssgan) cy@cy-PT6630WN:~/guo/Self-Supervised-GAN-master$  python main.py  --model SSLGAN_SN                                        --is_train True                                        --download False                                        --dataroot ../datasets/cifar10                                        --dataset cifar                                        --generator_iters 25000                                        --cuda True                                        --batch_size 64                                        --ssup
True
init model.
Namespace(batch_size=64, channels=3, cuda=True, dataroot='../datasets/cifar10', dataset='cifar', download='False', epochs=50, generator_iters=25000, is_train='True', load_D='False', load_G='False', loss='hinge', model='SSLGAN_SN', ssup=True)
True
Cuda enabled flag: True
WARNING:tensorflow:From /home/cy/guo/Self-Supervised-GAN-master/utils/tensorboard_logger.py:12: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

/home/cy/anaconda3/envs/ssgan/lib/python3.6/site-packages/torchvision/transforms/transforms.py:220: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Files already downloaded and verified
Files already downloaded and verified
/home/cy/guo/Self-Supervised-GAN-master/models/sslgan_sn.py:60: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  rot_prob = self.softmax(rot_logits)
  Discriminator iteration: 0/5, loss: 10.065513610839844, loss_rot: 3.9944543838500977
  Discriminator iteration: 1/5, loss: 5.343358039855957, loss_rot: 2.326465129852295
  Discriminator iteration: 2/5, loss: 2.720102548599243, loss_rot: 1.5358442068099976
  Discriminator iteration: 3/5, loss: 2.7146224975585938, loss_rot: 1.1560271978378296
  Discriminator iteration: 4/5, loss: 1.3078558444976807, loss_rot: 0.9942206144332886
Generator iteration: 0/25000, g_loss: 1.040503978729248, rot_loss: 0.4081612825393677
Models save to ./generator.pkl & ./discriminator.pkl
Generator iter: 0, Time: 1.582162857055664, FID: 352.5067769141092
WARNING:tensorflow:From /home/cy/guo/Self-Supervised-GAN-master/utils/tensorboard_logger.py:16: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

Traceback (most recent call last):
  File "main.py", line 34, in <module>
    main(args)
  File "main.py", line 22, in main
    model.train(train_loader)
  File "/home/cy/guo/Self-Supervised-GAN-master/models/sslgan_sn.py", line 217, in train
    d_loss_real.backward(one, retain_graph=True)
  File "/home/cy/anaconda3/envs/ssgan/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cy/anaconda3/envs/ssgan/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 10.76 GiB total capacity; 9.71 GiB already allocated; 47.56 MiB free; 9.88 GiB reserved in total by PyTorch)

**Comment by larry-11** [comment]
@gden138 It seems that you try to put too much data on CUDA. Reduce the batch_size or check your GPU and kill some useless process.

**Comment by gden138** [comment]
Thank you. It's ok .
I modify ops.py 
rows: 127-130  
if self.up_sampling:
            if hasattr(torch.cuda, 'empty_cache'):
	            torch.cuda.empty_cache()
            with torch.no_grad():
              return self.upsample(input) + x
        else:
            return input + x

**Comment by larry-11** [comment]
@gden138  Great. Thanks for your reminder!

**Comment by gden138** [comment]
You are welcome.  
Why is there no code for classification?  May I add your QQ ?My qq:120828069
